In [1]:
from feature_extraction import extract_all_features

In [9]:
!pip install pandas
import pandas as pd

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Faheem Iqbal\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Faheem Iqbal\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Faheem Iqbal\AppData\Roaming\Python\Python311\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Faheem Iqbal\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 4.2 MB/s eta 0:00:03
   ------- -------------------------------- 1.8/9.9 MB 4.8 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.9 MB 4.9 MB/s eta 0:00:02
   ---------------- ----------------------- 4.2/9.9 MB 5.0 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 5.0 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 4.7 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 4.2 MB/s  0:00:02
Installing collected packages: pandas
Successfully installed pandas-3.0.3

In [7]:
import os
print(os.getcwd())

d:\1.1_INternship

In [ ]:
url = "https://raw.githubusercontent.com/GregaVrbancic/Phishing-Dataset/master/dataset_full.csv"

df = pd.read_csv(url)

In [ ]:
df.head()

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,3,0,0,1,0,0,0,0,0,0,...,1,2,0,892,0,0,0,0,0,1
1,5,0,1,3,0,3,0,2,0,0,...,1,2,1,9540,1,0,0,0,0,1
2,2,0,0,1,0,0,0,0,0,0,...,1,2,3,589,1,0,0,0,0,0
3,4,0,2,5,0,0,0,0,0,0,...,1,2,0,292,1,0,0,0,0,1
4,2,0,0,0,0,0,0,0,0,0,...,1,2,1,3597,0,1,0,0,0,0

In [ ]:
df["phishing"].value_counts()

phishing
0    58000
1    30647
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88647 entries, 0 to 88646
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 75.7 MB

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
x = df.drop("phishing", axis=1)
y = df["phishing"]

In [ ]:
print("x shape:", x.shape)
print("y shape:", y.shape)

x shape: (88647, 111)
y shape: (88647,)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(70917, 111)
(17730, 111)
(70917,)
(17730,)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = rf.predict(x_test)
print(y_pred[:10])

[0 0 0 0 0 0 0 1 0 0]

In [ ]:
print(y_test[:10].values)

[0 0 0 0 0 0 0 1 0 0]

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy", accuracy*100,"%")

Accuracy 96.9825155104343 %

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11315   297]
 [  238  5880]]

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98     11612
           1       0.95      0.96      0.96      6118

    accuracy                           0.97     17730
   macro avg       0.97      0.97      0.97     17730
weighted avg       0.97      0.97      0.97     17730

In [ ]:
import joblib
joblib.dump(rf,"phishing_rf_model.pkl")

['phishing_rf_model.pkl']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt:

In [ ]:
import joblib

joblib.dump(
    rf,
    "/content/drive/MyDrive/Phishing_rf_model.pkl"
)

['/content/drive/MyDrive/Phishing_rf_model.pkl']

In [ ]:
for i, col in enumerate(df.columns):
    print(i, col)

0 qty_dot_url
1 qty_hyphen_url
2 qty_underline_url
3 qty_slash_url
4 qty_questionmark_url
5 qty_equal_url
6 qty_at_url
7 qty_and_url
8 qty_exclamation_url
9 qty_space_url
10 qty_tilde_url
11 qty_comma_url
12 qty_plus_url
13 qty_asterisk_url
14 qty_hashtag_url
15 qty_dollar_url
16 qty_percent_url
17 qty_tld_url
18 length_url
19 qty_dot_domain
20 qty_hyphen_domain
21 qty_underline_domain
22 qty_slash_domain
23 qty_questionmark_domain
24 qty_equal_domain
25 qty_at_domain
26 qty_and_domain
27 qty_exclamation_domain
28 qty_space_domain
29 qty_tilde_domain
30 qty_comma_domain
31 qty_plus_domain
32 qty_asterisk_domain
33 qty_hashtag_domain
34 qty_dollar_domain
35 qty_percent_domain
36 qty_vowels_domain
37 domain_length
38 domain_in_ip
39 server_client_domain
40 qty_dot_directory
41 qty_hyphen_directory
42 qty_underline_directory
43 qty_slash_directory
44 qty_questionmark_directory
45 qty_equal_directory
46 qty_at_directory
47 qty_and_directory
48 qty_exclamation_directory
49 qty_space_directory
50 qty_tilde_directory
51 qty_comma_directory
52 qty_plus_directory
53 qty_asterisk_directory
54 qty_hashtag_directory
55 qty_dollar_directory
56 qty_percent_directory
57 directory_length
58 qty_dot_file
59 qty_hyphen_file
60 qty_underline_file
61 qty_slash_file
62 qty_questionmark_file
63 qty_equal_file
64 qty_at_file
65 qty_and_file
66 qty_exclamation_file
67 qty_space_file
68 qty_tilde_file
69 qty_comma_file
70 qty_plus_file
71 qty_asterisk_file
72 qty_hashtag_file
73 qty_dollar_file
74 qty_percent_file
75 file_length
76 qty_dot_params
77 qty_hyphen_params
78 qty_underline_params
79 qty_slash_params
80 qty_questionmark_params
81 qty_equal_params
82 qty_at_params
83 qty_and_params
84 qty_exclamation_params
85 qty_space_params
86 qty_tilde_params
87 qty_comma_params
88 qty_plus_params
89 qty_asterisk_params
90 qty_hashtag_params
91 qty_dollar_params
92 qty_percent_params
93 params_length
94 tld_present_params
95 qty_params
96 email_in_url
97 time_response
98 domain_spf
99 asn_ip
100 time_domain_activation
101 time_domain_expiration
102 qty_ip_resolved
103 qty_nameservers
104 qty_mx_servers
105 ttl_hostname
106 tls_ssl_certificate
107 qty_redirects
108 url_google_index
109 domain_google_index
110 url_shortened
111 phishing

In [3]:
url = "https://google.com"

features = extract_all_features(url)

print(len(features))

105

In [10]:
url = "https://google.com"

features = extract_all_features(url)

features_df = pd.DataFrame([features])

print(features_df.shape)

(1, 105)